name: portfolio_aslam_khan
description: Professional Flutter Web Portfolio for Mohd Aslam Khan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.2.1
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

